### ISSUE TITLE
v1.1.0 - save button always disabled with different dateformat

### ISSUE THREAD

**Issue by Diginix** [afuerhoff/ioBroker.fb-checkpresence#33] opened 2020-11-29 09:52 UTC
No matter whether I change something in the instance settings, the Save/Save+Close buttons are always grayed out/not available.
js-controller 3.1.6
nodejs 12.20.0
npm 6.14.9

**Comment by Ilovegym66** [comment] 2020-11-29 10:22
here it works fine, with Node 14, js-controller 3.1.6 and npm 6.14.9.
@Diginix is the instance running?

**Comment by afuerhoff** [comment] 2020-11-29 11:02
The save button is only activated if the configuration settings are correct. Is a new feature in version 1.1.0.
When the cell lost the focus then you have a red or green underline.

**Comment by Diginix** [comment] 2020-11-29 12:43
I want to activate the Mesh Info:
![image](https://user-images.githubusercontent.com/39678667/100542052-2da8bf80-3248-11eb-9925-ef6eb69af5ea.png)

If i change anything else, it kept still inactive. The instance is proper connected to the FB (status green)

But I've found out that at least one "family member" must be set to be able to save any other setting. Maybe a wrong dependcy check in code. There is no hint that this feature must be used.

**Comment by Diginix** [comment] 2020-11-30 17:09
The problem seems to be the date format.
No matter what correct definition I have set, it is highlighted as invalid.
![image](https://user-images.githubusercontent.com/39678667/100640297-8e162a80-3336-11eb-81c4-f97e868ef410.png)

The only allowed dateformat is yyyy.mm.dd HH:MM:ss.

**Comment by afuerhoff** [comment] 2020-11-30 19:44
It's a bug. I've just checked this. The problem is the minus in the format string.
As workaround you can change the dateformat value in the object section of ioBroker from the id "system.adapter.fb-checkpresence.0". Here you can edit the raw value and change the dateformat.
![image](https://user-images.githubusercontent.com/50245893/100656136-895c7100-334c-11eb-97eb-c9ac7d913b82.png)
In the next version this bug is fixed.

**Comment by Diginix** [comment] 2020-11-30 21:56
Good to know that it is a small bug, that is easy to fix. I can wait.

**Comment by afuerhoff** [comment] 2021-01-13 22:35
Hi! Can you test the version 1.1.2 on Github.

**Comment by afuerhoff** [comment] 2021-01-15 16:27
I have updated the adapter on Github. Please install the bugfixed version for testing.

**Comment by Diginix** [comment] 2021-01-16 20:56
Works for me.

**Comment by afuerhoff** [comment] 2021-06-02 16:46
Fixed with 1.1.4

**Closed by afuerhoff** 2021-06-02 16:46 UTC
Labels: bug
