### ISSUE TITLE
Fritzbox 7581(fw7.14) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

### ISSUE THREAD

**Issue by tim4849** [afuerhoff/ioBroker.fb-checkpresence#46] opened 2021-05-23 10:13 UTC
Hello, I have 3 instances of the adapter running. See the following error descriptions. All Fritz boxes are configured in the same way and enabled for access. 
The Fritzbox is connected over the WAN-Port to a Fiber-Modem, therefore DSL is deactivated.

Adapter version is 1.1.4 - what's going wrong?
Thanks in advance!  

Instance 1: 7590 (fw7.21) works fine
------------------------------------------------------------------------------------------------------------
### Instance 2: 7581 (fw7.14) I see the following entries in the log:

fb-checkpresence.1 | 2021-05-23 11:56:09.125 | info | (5544) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
fb-checkpresence.1 | 2021-05-23 11:56:09.124 | info | (5544) terminating
fb-checkpresence.1 | 2021-05-23 11:56:08.622 | info | (5544) cleaned everything up ...
fb-checkpresence.1 | 2021-05-23 11:56:08.620 | info | (5544) Got terminate signal TERMINATE_YOURSELF
fb-checkpresence.1 | 2021-05-23 11:56:08.470 | warn | (5544)  onReady:  Fb init: checkServices: checkService Error service  X_AVM-DE_HostFilter-DisallowWANAccessByIP is not supported! Can not find  service file! Feature is deactivated
fb-checkpresence.1 | 2021-05-23 11:56:07.143 | info | (5544) starting. Version 1.1.4 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v12.21.0, js-controller: 3.3.10

**------------------------------------------------------------------------------------------------------------
Instance 3: 7530 (fw7.25) Works only with disable "SSL" Flag

**Comment by afuerhoff** [comment] 2021-05-24 16:43
Hello, I have a new test version uploaded to github. Please install and test it.

**Comment by tim4849** [comment] 2021-05-25 07:37
Hello thanks for yur quick reaction. Where can I find the test version?
Thanks in advance!

**Comment by afuerhoff** [comment] 2021-05-25 08:25
You have to install with url https://github.com/afuerhoff/ioBroker.fb-checkpresence
In the adapter view ( expert view) over the github cat.

**Comment by afuerhoff** [comment] 2021-05-25 16:45
What is the problem with instance 3 with SSL activated? Can you provide the log with loglevel debug from start of adapter to the error.

With option SSL = true is the normal case. Currently I have two cases with SSL is not working. You are the second case.
The option is a work around for this special case, but I cannot reproduce it on my side. Therefore it is hard to eliminate this error.

**Comment by tim4849** [comment] 2021-05-25 18:34
Of course, here we go:
- configs: SSL, FB-devices- Mesh and Guest
- when starting first gets green, then goes in warning state (see getExtIp)



fb-checkpresence.2 | 24283 | 2021-05-25 20:31:17.537 | debug | loop main ends after 12,15346620 s
-- | -- | -- | -- | --
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:17.532 | warn | getExtIp:
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:03.518 | debug | loop family ends after 0,2560610 s
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:02.515 | info | loop successfully started
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:02.514 | info | states successfully subscribed
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:02.514 | warn | infoNoFamilyMembers: no family members defined! Objects are not created!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:02.507 | info | createGlobalObjects finished successfully
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.804 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.803 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.803 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.802 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.800 | warn | You should then manually delete the old states!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.800 | warn | In  an future version some states are not more existent. Please use  compatibility = false to switch to the new handling of the states!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.778 | warn | Layer3Forwarding1-GetDefaultConnectionService is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.778 | warn | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.778 | warn | WANPPPConnection1-ForceTermination is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.778 | warn | DeviceConfig1-Reboot is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.777 | warn | X_AVM-DE_HostFilter-GetWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.777 | warn | X_AVM-DE_HostFilter-DisallowWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.777 | warn | DeviceInfo1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.776 | warn | WLANConfiguration3-GetSecurityKeys is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.776 | warn | WLANConfiguration3-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.776 | warn | WLANConfiguration3-SetEnable is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.775 | warn | WANIPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.775 | warn | WANPPPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.775 | warn | WANCommonInterfaceConfig1-GetCommonLinkProperties is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.774 | info | DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.774 | warn | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.774 | info | Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.773 | warn | Hosts1-X_AVM-DE_GetMeshListPath is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.773 | warn | Hosts1-X_AVM-DE_GetHostListPath is not supported! Feature is deactivated!
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.773 | info | configuration default connection: -
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.772 | debug | configuration filter delay: 15
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.772 | debug | configuration guest info: true
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.772 | debug | configuration qr code: false
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.771 | debug | configuration ssl: true
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.771 | debug | configuration compatibility: true
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.771 | debug | configuration whitelist: true
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.770 | debug | configuration mesh info: true
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.770 | debug | configuration fb-devices true
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.770 | debug | configuration familymembers: []
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.769 | debug | configuration familymembers count: 0
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.769 | debug | configuration dateformat: &lt;yyyy.mm.dd HH:MM:ss&gt;
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.769 | debug | configuration history: &lt;&gt;
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.768 | debug | configuration user: &lt;iobroker_tr064&gt;
fb-checkpresence.2 | 24283 | 2021-05-25 20:31:01.767 | info | start  fb-checkpresence.2: FRITZ!Box 7530 version: 164.07.25 ip-address:  "192.168.30.1" - interval devices: 1 min. - interval members: 60 s
fb-checkpresence.2 | 24283 | 2021-05-25 20:30:53.215 | info | starting. Version 1.1.4 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v12.21.0, js-controller: 3.3.10

**Comment by afuerhoff** [comment] 2021-05-25 18:50
Which access rights have the fritzbox user?  
Did you have insert an password?

**Comment by afuerhoff** [comment] 2021-05-25 19:48
If the interface to the fritzbox is hang up then I have the same behaviour. Please reboot the fritzbox and check if all is ok.

**Comment by tim4849** [comment] 2021-05-28 11:47
Thanks for your answer. Because the fritzbox is in my vacation home a reboot is not possible.
I`ll check this and give you info.

**Comment by Bzzz** [comment] 2021-06-06 22:36
1.1.5 fixes a hard crash on start of the adapter:

- info	"system.adapter.fb-checkpresence.0" disabled
- warn	(2860) onReady: Fb init: checkServices: checkService Error service WLANConfiguration3-SetEnable is not supported! Can not find service file! Feature is deactivated

I can't tell when this bug was introduced, this is an old Fritz 7362SL with WiFi disabled, using an external Mikrotik wAP ac instead. 1.1.5 now starts as expected, pulls in the device list as expected, and upon creation of family members, the presence objects are created. It still notes the above service file (as well as WLANConfiguration3-GetInfo, WLANConfiguration3-GetSecurityKeys, X_AVM-DE_HostFilter-DisallowWANAccessByIP and X_AVM-DE_HostFilter-GetWANAccessByIP) are not found, but as far as I can tell, it works just fine.

**Comment by afuerhoff** [comment] 2021-06-12 10:25
@Bzzz 
Hello, 
what fritzbox version do you have. 
For information: The files could not read when the version is an old version and do not support the used services.

**Comment by Bzzz** [comment] 2021-06-12 10:37
7.12, the latest that is available for the EOL 7362SL.

**Comment by afuerhoff** [comment] 2021-06-12 13:40
@Bzzz 
The 7.12 do not support the new features of the adapter.
Therefore the message in the log. 
My function that checks this has had  a bug and this was the failure in the adapter.  
Now it should run without failures and the not supported features were disabled correctly in the adapter.

**Comment by Bzzz** [comment] 2021-06-12 13:52
Indeed. So take this as verification of that build, thank you for your efforts, and have a nice weekend.

**Comment by afuerhoff** [comment] 2021-06-23 19:58
It is fixed with version v1.1.5.

**Closed by afuerhoff** 2021-06-23 19:58 UTC
Labels: bug
